#!/usr/bin/env bash
#
# ReMinix: quick rebuild of the MINIX part (kernel, servers, drivers, ...) and
# refresh of the disk image, without a full build.sh run. Called by
# docker/build.mk (target quick) inside the build container, with the same
# environment as hdimage (OBJ, DESTDIR, ...); see docs/docker-build.md.
#
# Needs a complete earlier "make hdimage" with the same SMP= setting: it
# reuses its tool chain, object tree, DESTDIR and the image work directory
# ($OBJ/work: extracted file tree and proto files).
#
#   1. nbmake dependall + install in each of QUICK_DIRS (into DESTDIR)
#   2. releasetools do-hdboot: kernel and boot modules -> boot/minix/.temp,
#      which test-i386 / run-i386 boot directly
#   3. image refresh: every file of $OBJ/work/fs that has a newer, different
#      copy in DESTDIR is replaced, the kernel directories get the new
#      .temp contents; then the partitions are written again as in
#      releasetools/x86_hdimage.sh (keep the two in sync). The new image is
#      written next to the old one and renamed over it, so a QEMU that still
#      has the old image open is not disturbed.
#
# Limits: new files (not in the last full image) and changes to sets lists,
# /etc files generated by the image scripts or headers used outside
# QUICK_DIRS need a full "make hdimage".
#
# env: QUICK_DIRS (default below), IMG (image file name), JOBS

set -eu

: ${QUICK_DIRS:="minix/lib minix/kernel minix/servers minix/fs minix/net minix/drivers"}
: ${IMG:=minix_x86.img}
: ${JOBS:=1}

NBMAKE=$OBJ/tooldir/bin/nbmake-i386
CROSS=$OBJ/tooldir/bin
WORK_DIR=$OBJ/work
ROOT_DIR=$WORK_DIR/fs

for f in "$NBMAKE" "$WORK_DIR/proto.root" "$IMG"; do
	[ -e "$f" ] || { echo "quick: $f missing -- run a full 'make hdimage' (same SMP=) first" >&2; exit 1; }
done

t0=$(date +%s)
stamp=$(mktemp)		# files installed from now on are "new"

echo ">>> 1. build and install: $QUICK_DIRS"
for d in $QUICK_DIRS; do
	echo ">>>    $d"
	"$NBMAKE" -j "$JOBS" -C "$d" dependall
	"$NBMAKE" -C "$d" install
done

echo ">>> 2. kernel and boot modules (releasetools do-hdboot)"
"$NBMAKE" -C releasetools do-hdboot >/dev/null

echo ">>> 3. image refresh"
n=0
# boot module directories of the image: same files as .temp
for kd in "$ROOT_DIR"/boot/minix_default "$ROOT_DIR"/boot/minix/*/; do
	[ -d "$kd" ] || continue
	for f in "$DESTDIR"/boot/minix/.temp/*; do
		t="$kd/$(basename "$f")"
		if [ -f "$t" ] && ! cmp -s "$f" "$t"; then
			cp "$f" "$t"
			n=$((n + 1))
		fi
	done
done
# everything else: files of the image tree with a newer, different copy in
# DESTDIR (only what step 1 installed is newer than the extracted tree)
while IFS= read -r rel; do
	src="$DESTDIR/$rel"
	if [ -f "$src" ] && ! cmp -s "$src" "$ROOT_DIR/$rel"; then
		echo "      $rel"
		cp "$src" "$ROOT_DIR/$rel"
		n=$((n + 1))
	fi
done < <(cd "$DESTDIR" && find . -path ./boot -prune -o -type f -newer "$stamp" -print |
	 sed 's,^\./,,' | while IFS= read -r r; do [ -f "$ROOT_DIR/$r" ] && echo "$r"; done)
rm -f "$stamp"
echo ">>>    $n file(s) replaced"

# --- partitions, as in releasetools/x86_hdimage.sh -------------------------
: ${BOOTXX_SECS=32}
: ${ROOT_SIZE=$((  128*(2**20) - ${BOOTXX_SECS} * 512 ))}
: ${HOME_SIZE=$((  128*(2**20) ))}
: ${USR_SIZE=$((  1792*(2**20) ))}

new="$IMG.quick.$$"
rm -f "$new"
ROOT_START=$BOOTXX_SECS
_ROOT_SIZE=$("$CROSS"/nbmkfs.mfs -d -b $((ROOT_SIZE / 512 / 8)) -I $((ROOT_START * 512)) "$new" "$WORK_DIR"/proto.root)
_ROOT_SIZE=$((_ROOT_SIZE / 512))
USR_START=$((ROOT_START + _ROOT_SIZE))
_USR_SIZE=$("$CROSS"/nbmkfs.mfs -d -b $((USR_SIZE / 512 / 8)) -I $((USR_START * 512)) "$new" "$WORK_DIR"/proto.usr)
_USR_SIZE=$((_USR_SIZE / 512))
HOME_START=$((USR_START + _USR_SIZE))
_HOME_SIZE=$("$CROSS"/nbmkfs.mfs -d -b $((HOME_SIZE / 512 / 8)) -I $((HOME_START * 512)) "$new" "$WORK_DIR"/proto.home)
_HOME_SIZE=$((_HOME_SIZE / 512))
"$CROSS"/nbpartition -m "$new" "$BOOTXX_SECS" 81:${_ROOT_SIZE}* 81:${_USR_SIZE} 81:${_HOME_SIZE} >/dev/null
"$CROSS"/nbinstallboot -f -m i386 "$new" "$DESTDIR"/usr/mdec/bootxx_minixfs3 >/dev/null
mv -f "$new" "$IMG"

echo ">>> done in $(( $(date +%s) - t0 ))s: $IMG, kernel and modules in $DESTDIR/boot/minix/.temp"
