/*
 * abi64 reference dumper: linked with the -m32 probes, prints their table
 * as a C initializer (abi64_ref32.h) -- the i386 layout every test variant
 * compares itself with.  Built and run by module.mk.
 */
#include <stdio.h>

#include "abi64.h"

int
main(void)
{
	const struct abi64_ent *e;

	printf("/* Generated by abi64/dump.c from the -m32 probes. */\n");
	printf("static const struct abi64_ent abi64_ref32[] = {\n");
	for (e = __start_abi64_tab; e < __stop_abi64_tab; e++)
		printf("\t{ \"%s\", \"%s\", \"%s\", %lu, %lu, %lu },\n",
		    e->cat, e->type, e->field, e->size, e->align, e->off);
	printf("};\n");
	return 0;
}
