service vbfs
{
        ipc
                SYSTEM pm vfs rs ds vm vbox
        ;
        vm
                SETCACHEPAGE
                CLEARCACHE
        ;
	with	       vfs;	# SMP: on the cpu of vfs (calls go vfs <-> fs/disk)
};

